apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mesh-six

images:
  - name: registry.bto.bar/mesh-six/orchestrator
    newTag: latest
  - name: registry.bto.bar/mesh-six/simple-agent
    newTag: latest
