apiVersion: v1
kind: Service
metadata:
  name: researcher-agent
  namespace: mesh-six
  labels:
    app: researcher-agent
    app.kubernetes.io/part-of: mesh-six
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: researcher-agent
