apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-six
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.bto.bar/jay/mesh-six.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mesh-six
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
