apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: project-manager-ntfy-reply
  namespace: mesh-six
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mesh-six.bto.bar`) && PathPrefix(`/ntfy-reply`)
      kind: Rule
      services:
        - name: project-manager
          port: 80
  tls:
    certResolver: letsencrypt
