apiVersion: v1
kind: Service
metadata:
  name: context-service
  namespace: mesh-six
spec:
  selector:
    app: context-service
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
