apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agent-pubsub
  namespace: mesh-six
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      secretKeyRef:
        name: rabbitmq-secret
        key: url
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "2"
    - name: requeueInFailure
      value: "true"
    - name: publisherConfirm
      value: "true"
    - name: prefetchCount
      value: "1"
