apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-statestore
  namespace: mesh-six
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis-master.redis-system:6379"
    - name: redisPassword
      secretKeyRef:
        name: redis-secret
        key: password
    - name: keyPrefix
      value: "mesh-six-actors:"
    - name: actorStateStore
      value: "true"
  scopes:
    - llm-service
    - architect-agent
