apiVersion: v1
kind: Service
metadata:
  name: event-logger
  namespace: mesh-six
  labels:
    app: event-logger
    app.kubernetes.io/part-of: mesh-six
spec:
  type: ClusterIP
  selector:
    app: event-logger
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
