apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: onboarding-service
  namespace: mesh-six
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mesh-six.bto.bar`) && PathPrefix(`/onboard`)
      kind: Rule
      services:
        - name: onboarding-service
          port: 80
  tls:
    certResolver: letsencrypt
