apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboarding-service
  namespace: mesh-six
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onboarding-service-pod-reader
  namespace: mesh-six
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onboarding-service-pod-reader
  namespace: mesh-six
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onboarding-service-pod-reader
subjects:
  - kind: ServiceAccount
    name: onboarding-service
    namespace: mesh-six
